name: grainos auto build

on:
  push:
    branches:
      - main  # main main main main main main main main

jobs:
  build:
    runs-on: ubuntu-latest # ubuntu is powering the github action lol L

    steps:
    - name: checkout repo
      uses: actions/checkout@v2

    - name: Setup Arch Linux environment
      uses: RangHo/setup-arch@v1.1.0
      with:
        mirror: https://geo.mirror.pkgbuild.com
        packages: "arch-install-scripts archiso awk dosfstools e2fsprogs erofs-utils findutils grub gzip libarchive libisoburn mtools openssl pacman sed squashfs-tools shellcheck python-docutils"


    - name: Build Archiso
      run: | 
        sudo mkarchiso -v archiso
      shell: arch.sh {0}
